title: "Web Documentation"
version: "0.0.1"
logo: "logo.svg" # See font-awesome icons
last_updated: "August 5, 2015"

welcome_message: "Web Documentation Welcome!"
welcome_copy: "Here are some examples of the typography elements included with the framework for quick and easy way to create and edit your content."
